name: Validate Commit

on:
  push:
    branches:
      - hidden
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run validation script
        run: node script.js
